# define limits
define user ask off topic
  "How's the weather today?"
  "What's your opinion on the latest political news?"
  "What are the best tourist attractions in Paris?"

define bot explain cant off topic
  "I cannot answer to your question because I'm programmed to assist only with movies."

define flow
  user ask off topic
  bot explain cant off topic